sudo: false
language: node_js
node_js:
- "10"
script: bash ./deploy.sh
branches:
  only:
  - master
env:
  global:
    - GH_REF: github.com/openactive/routes.git
    - secure: "SzWSONo39xyQBrQyYO1LO5DOJld/09nfSolMexd7MMA3y+HNUx0dt/U+ljhhvFhZIj8/2h7b5OExdmcIsvK6itxDFHDF/XKXirZS0dAIXyFEpS4IEpcMeEtfZyf/2JUZN6QdGi2DwYm+o5qH3cTpi7/vtIcSWxhLdBOAgA934GfA8IM4gCDvbiF/HlhcOmqZwnApr1YUnsbLQBmjrKn2ZP5sWCjqmlUSoTbAffTU4D+NuKLHLaYepnyB5elkyUXhbOQObF91Bs6ZQTovbJAHyxCB2LTP/9yplJso7Ugu/UVteqXmFHNT0+CLmtGl4BvM4QNxcrnJOGPxBnGG6VSGe53BvE8rsOOWN3Sug2WXu+BG4gFAC4rtEXdE0evsVz/02tGz4oX4d/JScFFq5kpUjvxB8K9NRjxI2Vo8h8rSfL3YXd7rTu7H0TOy5S8X3TqDmBgoenSJ/fTxhSiffOsY2m/Ejmt8hOhaNof9LdeSUp31wDXQVQhxscXpi6QaF0NsvwHAbShsk6ubRQa2yM03NR4ka0m4qNyekM5QSmSj/lTJn0vpabXl9NPQqUdvR1J3XT9sML6s8GmhrrqGyQHOCVWj6F8FqBBO3GZaf5OZHDgoKvCMfWmnO2KYqjMqdhZI0Xv1ygTvmtElMVyOzcDVbQDYbVzh6gSAypz7WNDO5zc="
