sudo: false
language: node_js
node_js:
- '10'
script: bash ./deploy.sh
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/openactive/routes.git
  - secure: Gt6MQzs3qrOc8lGqw8ugTakQtQIlGPlzfkxblFtQO7pnQC9KAdk2QWbFDAFB3mSRjFdcILdJTR5Vx4fFdCLTVVHtVg0S1LoeXRFydqUmkEoBImswbCuDfzkYriRXwI4zO6I6cqU5byb7bMpUDRoVCFzGgMYK03qfdSbMsy2TgzIfxs/hvtSroCWH5SZ39rmqwHxh7IZaDjGhPG1wjsEDvaF5DM5CsBNfQJgffIzDnNuY9hmfXpzdttQmxL4rVoztKVU9GIlCsUxl0mkvJoUsHc8E0Okgye0mEEkeErQ4xMMCeRjX/1m/HcmLAtMG5TU9aCLiuOlDP6dfhhtExvf8IXumU4wSZqQMP2KwaRNEqkjzY+/n4Gk6Q3kY9NIVUZibkwKWCrCWkLGuYrR/x+lW53gPxX5NKIsVtYMn7s/r2tnRJLu2RhA8aWqjBMQWc7VyQsMm2E7LBNu2l2ySU7fZK0P1fvOGGLzvu3DC9r5B+nhC8D/VqU/ysBAQE5vxkrszxpa8BygLmu5AXoPbIEls+vm8dcPZr5lE9UVBpK0pWJg7w8bSpWn4WvaDlvU8KMv7AUDx9SVeT/whZtm6teqhXirp9lLgXLUex4Ho/9ypP/7ovYmXKJx3w5Zia6wd4c1EWpLgE/JlPI2Y1UcPc/JW5lljbTsr2Ls4UxZS45/g2Oc=
  - secure: o9l4nB307R7oncruqmFGpT79f8hCFyWN1agsZrTQMycfxNeYyZ3KWC9tTXbvUVfY8ThYfRF0YE0fbPa+6P1jxKHz5pDl7muNFYRFdOrJ0IZCSmvie90kIAb2IdLProffY9MuOun1RXFeEehSCrU5fA6JNtm3DaRfV4T9YYCbcj+669pSOSTweznySOsIWbfbf3INvQGbQIvWEMPnGpTwY3rCIlhKyOqKHELcHkyCODTsF0w8B3vuNfBYYuSH22Opw5NxONADtE6QG4YxDAnPZC8HV7WnehSDjy8iwKeUQlWf2/POQeJpeRucgtIV0bwV8rsxG1KhrwNgSrPasrW6jtno394NM6m0EuvOhJ4k0TzjpGEHGoClrCCNBuWRGBztMkpU0gMXP0tpujUKqqIJ3lDiSmTfAVjVQ53/YqKwLlmiHTEWTiDl/2ry8KFHPJhRgyTdXECiLzHz0l7Fz+m4g7X6gNGzid3WA8af6gM4lACvzonqdSOeIUm8nr+I3aFJy7nzLsjOyhhbjJeV0dtDIAYxax681mjqTg0/1wAiyluR/Jh32TCguW2UI73hD/M8MyloxEoCvo4jIr/nbMeB7Jz+WCP/TGXo+TNEiVCcctccieMnN+YbVM5qulpXqcDO0q83CR6I0nTq7PQ58KpwBxbhcch40jtI3ivK0UiIu78=
