sudo: false
language: node_js
node_js:
- '10'
script: bash ./deploy.sh
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/openactive/routes.git
  - secure: mtcPFCJN2xGoGetvw+KSrhc+mEvER/hGHxPP5GLXqHykZjG4X3EgTaAYzUdIOIKp6aoRldUets4qqx7MFcHYL4pU3y/PGhVDqhcsRxMgnFOdm8kyaVF/jS2PrHzTw320k+ygg6k9RsWVp5ydLMCJn7ykhqTFGpf2uYuuBfl8nqtwzFCGqthtEbF9duYjdcFurmFhTGHHr91tUfHkjr/rjfKBTHop9xbwYFZH8778UCKVNhUuO1IRgclbGSivO2iwq2HmyUDeJoXEBCi+V/T1IFSqDdeft9HbbK3t1+S2wIcFavlW6jJg3aOMdZJD/igx3jGVUhsmnICmEsGSa/9xayS0LXRueMcOBOjT2WTBS1vpiW8dRH4FuTWci9WnJNG/8EZL6QIeSYwHqrKxm/AWeyojLJBILnjputjyoUnYngApQqi8z9ADRng+bVniu/j0NdBRCCMC26R2rXZmBN3HVeZUT1lCyEFL0fqQHbuB67tLcp/2ST52SNGJG5n68FOqqcK3cKka4d49Vd6C/Y0OB24ud38KUcjqpUTDsQ1y84MJUVZI/IyPPUldQy5IIg/8D+gYQZRbjWlRLM/xf2Tqcl77NWnIBrTwVBrLVCtyBdu1djynZ1TdHB5vG57vTMc5UJMzSiOIPpn4RZhIwWgZdZoPwVG+0rDPcEdtxKE8oL0=
