sudo: false
language: node_js
node_js:
- '10'
script: bash ./deploy.sh
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/openactive/routes.git
  - secure: H+4cU4XN9yAaxZpYW7jMIUuZV9c9RWH9I/94FqJSlKgvNcV7mw01kfKgCNsT3Gl1dzaXtm/HImb99izOIubHH+01unynkRFx/TRZd0aDSzYlroIKbHsqLRM4ohWnKZtd/mT5D4xZ73gvyI/6CrjdxRgoigDIGhRQH926uxfmOg7liaYaxEmzW9qxtXMT/7COm0rR3emia3GmO+Mu+1OPeCCJ2/TeMCuCoO8kCpvItTgfUpCLUipjbHHo+npa4DHrcW/vqDibzbn5S4Jk2romT29a3A03ma+uzv2Vghi63Kstd5nSjCefjeFocmulTRYMnd/Tyz3BK3My8G2imN06NG6Dko5gX57zK1n05dTwE4stMjECUcueecl6lz8GSN050PaRnPje5S7RDrlBa2guH/7pw4sRxQIJQ55+u1fY29sB1UW6dTv55a4lIO/AO+5OivXngllQPWq83EFSIqA1Vp91nil0mSNcit/EWci6O+1P/fECOia6mfFQCUzT+cws98hCbmqXKEFw7rsVnzSumUEFiqUVlJ37eGBM3huTDh3vTK1XnrwpFSDVGTwwW02sBhh8CBmXQM4vh7jxKgENErict9o+guGjWMclbvLIY8HOAbg28SJ2w2hJhMxtnV49KnOQ5rqJ/X9GMZPOpxX+dwZqX4W98pCfAaClYnYg3tU=
