sudo: false
language: node_js
node_js:
- '10'
script: bash ./deploy.sh
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/openactive/routes.git
before_install:
- openssl aes-256-cbc -K $encrypted_9576e94873d0_key -iv $encrypted_9576e94873d0_iv
  -in deploy_key.enc -out deploy_key -d
